### ISSUE TITLE
Error running long workflow

### ISSUE THREAD

**Issue by johnbradley** [Duke-GCB/calrissian#58]
Using the docker image `dukegcb/calrissian:0.3.1` I received the following error when running the [exomeseq-gatk4-preprocessing.cwl](https://github.com/Duke-GCB/bespin-cwl/releases/download/v0.9.4/exomeseq-gatk4-preprocessing.cwl) workflow.
```
Traceback (most recent call last):
  File "/usr/local/bin/calrissian", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/calrissian/main.py", line 83, inmain
    write_report(parsed_args.usage_report)
  File "/usr/local/lib/python3.6/site-packages/calrissian/report.py", line 343,in write_report
    json.dump(Reporter.get_report().to_dict(), f, indent=4, default=default_serializer)
  File "/usr/local/lib/python3.6/site-packages/calrissian/report.py", line 290,in to_dict
    result = super(TimelineReport, self).to_dict()
  File "/usr/local/lib/python3.6/site-packages/calrissian/report.py", line 39, in to_dict
    result['elapsed_hours'] = self.elapsed_hours()
  File "/usr/local/lib/python3.6/site-packages/calrissian/report.py", line 35, in elapsed_hours
    return self.elapsed_seconds() / SECONDS_PER_HOUR
  File "/usr/local/lib/python3.6/site-packages/calrissian/report.py", line 27, in elapsed_seconds
    delta = self.finish_time - self.start_time
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
```
Command was:
```
calrissian --default-container debian:stretch-slim --tmp-outdir-prefix /bespin/tmpout/ \
  --outdir /bespin/output-data/results/ --max-ram 120G --max-cores 52 \
  --usage-report /bespin/output-data/job-94-jpb67-resource-usage.json \
  /bespin/job-data/workflow/exomeseq-gatk4-preprocessing.cwl /bespin/job-data/job-order.json
```

**Comment by johnbradley** [comment]
Checked a little further up in the logs and found:
```
Unhandled error, try again with --debug for more information:
  [Errno 28] No space left on device: '/bespin/tmpout/06hunyuc'
```
Closing this issue for now.

**Comment by dleehr** [comment]
I'm going to reopen this, because I too see the reporting errors when the process fails early on. It's a valid case that should be handled (and not confused by piling on an exception about the report that's not helpful)
